/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim':        '#fbba64',
        'tertiary-container':       '#5c9ccd',
        'surface-dim':              '#17130d',
        'on-secondary-fixed-variant':'#7b2f00',
        'on-primary-fixed-variant': '#643f00',
        'on-secondary':             '#571f00',
        'tertiary':                 '#90cdff',
        'inverse-primary':          '#845400',
        'surface':                  '#17130d',
        'on-primary-fixed':         '#2a1800',
        'on-tertiary-fixed':        '#001e30',
        'error':                    '#ffb4ab',
        'on-surface':               '#ece0d6',
        'on-primary-container':     '#442900',
        'surface-variant':          '#3a342d',
        'primary-fixed':            '#ffddb6',
        'on-secondary-fixed':       '#351000',
        'primary-container':        '#c58b3a',
        'surface-tint':             '#fbba64',
        'inverse-on-surface':       '#362f29',
        'inverse-surface':          '#ece0d6',
        'on-tertiary-fixed-variant':'#004b72',
        'error-container':          '#93000a',
        'surface-container-lowest': '#120d08',
        'on-surface-variant':       '#d5c4b2',
        'surface-container-high':   '#2f2923',
        'outline-variant':          '#514537',
        'on-secondary-container':   '#571f00',
        'secondary-container':      '#ff6a00',
        'surface-bright':           '#3f3831',
        'on-tertiary-container':    '#00324d',
        'on-background':            '#ece0d6',
        'surface-container-low':    '#201b15',
        'outline':                  '#9d8e7e',
        'on-error-container':       '#ffdad6',
        'on-error':                 '#690005',
        'surface-container-highest':'#3a342d',
        'secondary-fixed-dim':      '#ffb694',
        'surface-container':        '#241f19',
        'on-tertiary':              '#003350',
        'on-primary':               '#462a00',
        'secondary-fixed':          '#ffdbcc',
        'background':               '#17130d',
        'tertiary-fixed':           '#cbe6ff',
        'secondary':                '#ffb694',
        'primary':                  '#fbba64',
        'tertiary-fixed-dim':       '#90cdff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs:               '4px',
        sm:               '12px',
        md:               '24px',
        base:             '8px',
        gutter:           '24px',
        xl:               '80px',
        'margin-mobile':  '20px',
        'margin-desktop': '64px',
        lg:               '48px',
      },
      fontFamily: {
        'body-md':           ['Inter', 'sans-serif'],
        'headline-lg':       ['Inter', 'sans-serif'],
        'label-sm':          ['Geist', 'sans-serif'],
        'display-mono':      ['Geist', 'sans-serif'],
        'headline-lg-mobile':['Inter', 'sans-serif'],
        'body-lg':           ['Inter', 'sans-serif'],
        'headline-xl':       ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md':           ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        'headline-lg':       ['32px', { lineHeight: '1.2',  letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-sm':          ['12px', { lineHeight: '1.0',  letterSpacing: '0.02em',  fontWeight: '600' }],
        'display-mono':      ['14px', { lineHeight: '1.5',  letterSpacing: '0.1em',   fontWeight: '500' }],
        'headline-lg-mobile':['28px', { lineHeight: '1.2',  fontWeight: '600' }],
        'body-lg':           ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
        'headline-xl':       ['48px', { lineHeight: '1.1',  letterSpacing: '-0.04em', fontWeight: '700' }],
      },
      keyframes: {
        ledPulse: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)', boxShadow: '0 0 5px #fbba64' },
          '50%':      { opacity: '0.5', transform: 'scale(0.8)', boxShadow: '0 0 2px #fbba64' },
        },
        scanline: {
          '0%':   { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(1000%)' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(30px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        pulseRed: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%':      { opacity: '0.7', transform: 'scale(1.1)' },
        },
        spin: {
          from: { transform: 'rotate(0deg)' },
          to:   { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'led-pulse':   'ledPulse 2s infinite ease-in-out',
        'scanline':    'scanline 4s linear infinite',
        'fade-in-up':  'fadeInUp 0.8s cubic-bezier(0.2,0.8,0.2,1) forwards',
        'pulse-red':   'pulseRed 2s infinite ease-in-out',
        'spin-slow':   'spin 10s linear infinite',
      },
      boxShadow: {
        glass: '0px 24px 48px rgba(0,0,0,0.5)',
        'primary-glow': '0 0 30px rgba(251,186,100,0.3)',
        'primary-glow-lg': '0 0 50px rgba(251,186,100,0.5)',
        'error-glow': '0 0 15px rgba(239,68,68,0.5)',
      },
    },
  },
  plugins: [],
}
